### ISSUE TITLE
Issue Buk

### ISSUE THREAD

**Issue by leowildman** [jaddison06/ocrpi#1]
When `make run` ran, makefile errors.

```
root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/ocrpi# python3 --version
Python 3.10.7
root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/ocrpi# python3 build/generate-makefile.py
root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/ocrpi# make run
python build/codegen.py generate.yaml ./generated
make: python: No such file or directory
make: *** [Makefile:27: generated.c] Error 127
```

**Comment by jaddison06** [comment]
Dearest Leo,

The build system assumes that the `python` command is synonymous with your python3 - could you post the output of `python --version`? The Python command used by the build system is configured on line 37 of `build/generate-makefile.py` - if you'd like to continue using your `python3` command then please don't be shy to update it there and regenerate the Makefile!

Yours as ever,

Jads

**Comment by leowildman** [comment]
**In addition**, you yourself use `python3` in your documentation, perhaps consistency would aid your users.

xx

**Comment by jaddison06** [comment]
Perhaps getting some bitches would aid you
