### ISSUE TITLE
Help with reading files?

### ISSUE THREAD

**Issue by leowildman** [jaddison06/ocrpi#3]
I'm trying to read some text from a file, but its not very happy with me... can I have some help?
```
myFile = openRead('sample.txt')
while NOT myFile.endOfFile()
        print(myFile.readLine())
endwhile
myFile.close()
```

output:

```
root@ubuntu-s-1vcpu-1gb-intel-fra1-01:~/ocrpi# ./ocrpi helloworld.ocr 
Parse error at token #9 (line 1, column 27)
'txt':
Expected close bracket after arguments
```

**Comment by jaddison06** [comment]
Hi Leo!

I would point you towards README.md, which states that string literals use double quotes only :)

All best,

Jads

**Comment by leowildman** [comment]
Yep, tried that - now getting
```
Unknown Variable
```

Thanks,

**Comment by jaddison06** [comment]
Well done! Unfortunately ocrpi isn't ready for production yet :( - the unknown variable message comes from your use of the openRead function, which doesn't currently exist in the standard library. For better results try something simpler, like `print` <3
